-- ═══════════════════════════════════════════════════════════════════
-- SurrealTalentConfig_SSUI.lua  —  Shared talent tree definitions
-- Auto-generated by SDB Editor  —  DO NOT EDIT MANUALLY
-- Used by both client (SSUI addon) and server (Eluna validation)
-- ═══════════════════════════════════════════════════════════════════

-- Register with SSUI so this file is sent to clients.
-- Do NOT wrap in if/else — SURREAL_TALENT_TREES must exist on BOTH sides.
local SSUI = SSUI or require("SSUI")
SSUI.AddAddon()

SURREAL_TALENT_TREES = {
    -- ══ WARRIOR (classId=1) ══
    [1] = {
        className = "WARRIOR",
        tabs = {
            [1] = {
                name = "Arms",
                tabId = 161,
                masteryTalentId = 2284,
                talents = {
                    [2284] = {row=1, col=1, maxRank=1, spells={674}},
                    [2305] = {row=1, col=2, maxRank=1, spells={100}},
                    [2286] = {row=2, col=1, maxRank=1, spells={29725}},
                    [2294] = {row=2, col=2, maxRank=1, spells={5308}},
                    [2287] = {row=3, col=1, maxRank=1, spells={674}},
                    [2309] = {row=3, col=2, maxRank=1, spells={46968}},
                    [2310] = {row=4, col=1, maxRank=1, spells={46917}},
                    [2308] = {row=4, col=2, maxRank=1, spells={6552}},
                    [2290] = {row=5, col=2, maxRank=1, spells={46924}},
                },  -- talents
            },  -- Arms
            [2] = {
                name = "Fury",
                tabId = 164,
                masteryTalentId = 154,
                talents = {
                    [2284] = {row=1, col=1, maxRank=1, spells={674}},
                    [2305] = {row=1, col=2, maxRank=1, spells={100}},
                    [154] = {row=1, col=4, maxRank=1, spells={29801}, mastery=true},
                    [2289] = {row=1, col=12, maxRank=1, spells={23881}},
                    [2286] = {row=2, col=1, maxRank=1, spells={29725}},
                    [2294] = {row=2, col=2, maxRank=1, spells={5308}},
                    [2296] = {row=2, col=11, maxRank=1, spells={12867}},
                    [2293] = {row=2, col=12, maxRank=1, spells={56924}},
                    [2287] = {row=3, col=1, maxRank=1, spells={674}},
                    [2309] = {row=3, col=2, maxRank=1, spells={46968}},
                    [2297] = {row=3, col=11, maxRank=1, spells={56614}},
                    [2298] = {row=3, col=12, maxRank=1, spells={20243}},
                    [2310] = {row=4, col=1, maxRank=1, spells={46917}},
                    [2308] = {row=4, col=2, maxRank=1, spells={6552}},
                    [2304] = {row=4, col=11, maxRank=1, spells={50687}},
                    [2299] = {row=4, col=12, maxRank=1, spells={12328}},
                    [2290] = {row=5, col=2, maxRank=1, spells={46924}},
                    [2295] = {row=5, col=12, maxRank=1, spells={1680}},
                },  -- talents
            },  -- Fury
            [3] = {
                name = "Protection",
                tabId = 163,
                masteryTalentId = 138,
                talents = {
                    [2284] = {row=1, col=1, maxRank=1, spells={674}},
                    [2305] = {row=1, col=2, maxRank=1, spells={100}},
                    [140] = {row=1, col=4, maxRank=5, spells={12299, 12761, 12762, 12763, 12764}},
                    [142] = {row=1, col=4, maxRank=2, spells={12301, 12818}},
                    [150] = {row=1, col=4, maxRank=2, spells={12312, 12803}},
                    [153] = {row=1, col=4, maxRank=1, spells={12975}, flags=1},
                    [1652] = {row=1, col=4, maxRank=2, spells={29593, 29594}},
                    [2236] = {row=1, col=4, maxRank=1, spells={57499}},
                    [2247] = {row=1, col=4, maxRank=2, spells={59088, 59089}},
                    [144] = {row=1, col=5, maxRank=3, spells={50685, 50686, 50687}},
                    [147] = {row=1, col=5, maxRank=2, spells={12797, 12799}},
                    [148] = {row=1, col=5, maxRank=1, spells={50720}, prereqs={{id=152, rank=0}}, flags=1},
                    [151] = {row=1, col=5, maxRank=2, spells={12313, 12804}},
                    [152] = {row=1, col=5, maxRank=1, spells={12809}, flags=1},
                    [1601] = {row=1, col=5, maxRank=5, spells={12298, 12724, 12725, 12726, 12727}},
                    [1653] = {row=1, col=5, maxRank=3, spells={29140, 29143, 29144}},
                    [1666] = {row=1, col=5, maxRank=1, spells={20243}, flags=1},
                    [1871] = {row=1, col=5, maxRank=3, spells={46951, 46952, 46953}, prereqs={{id=1666, rank=0}}},
                    [1872] = {row=1, col=5, maxRank=1, spells={46968}, flags=1},
                    [138] = {row=1, col=6, maxRank=5, spells={12297, 12750, 12751, 12752, 12753}, mastery=true},
                    [141] = {row=1, col=6, maxRank=3, spells={12287, 12665, 12666}},
                    [146] = {row=1, col=6, maxRank=3, spells={12308, 12810, 12811}},
                    [149] = {row=1, col=6, maxRank=2, spells={12311, 12958}},
                    [702] = {row=1, col=6, maxRank=5, spells={16538, 16539, 16540, 16541, 16542}},
                    [1654] = {row=1, col=6, maxRank=2, spells={29598, 29599}},
                    [1660] = {row=1, col=6, maxRank=3, spells={29787, 29790, 29792}},
                    [1870] = {row=1, col=6, maxRank=2, spells={46945, 46949}},
                    [1893] = {row=1, col=6, maxRank=3, spells={47294, 47295, 47296}},
                    [2246] = {row=1, col=6, maxRank=2, spells={58872, 58874}},
                    [2286] = {row=2, col=1, maxRank=1, spells={29725}},
                    [2294] = {row=2, col=2, maxRank=1, spells={5308}},
                    [2287] = {row=3, col=1, maxRank=1, spells={674}},
                    [2309] = {row=3, col=2, maxRank=1, spells={46968}},
                    [2310] = {row=4, col=1, maxRank=1, spells={46917}},
                    [2308] = {row=4, col=2, maxRank=1, spells={6552}},
                    [2290] = {row=5, col=2, maxRank=1, spells={46924}},
                },  -- talents
            },  -- Protection
        },  -- tabs
    },  -- WARRIOR

    -- ══ PALADIN (classId=2) ══
    [2] = {
        className = "PALADIN",
        tabs = {
            [1] = {
                name = "Holy",
                tabId = 381,
                masteryTalentId = 2304,
                talents = {
                    [2286] = {row=1, col=2, maxRank=1, spells={20271}},
                    [2304] = {row=1, col=4, maxRank=1, spells={53563}, mastery=true},
                    [2310] = {row=1, col=12, maxRank=1, spells={54155}},
                    [2298] = {row=2, col=1, maxRank=1, spells={1038}},
                    [2302] = {row=2, col=2, maxRank=1, spells={26573}},
                    [2291] = {row=2, col=3, maxRank=1, spells={20166}},
                    [2312] = {row=2, col=11, maxRank=1, spells={47515}},
                    [2311] = {row=2, col=12, maxRank=1, spells={53592}, prereqs={{id=2310, rank=1}}},
                    [2297] = {row=3, col=1, maxRank=1, spells={1044}},
                    [2299] = {row=3, col=2, maxRank=1, spells={642}},
                    [2288] = {row=3, col=3, maxRank=1, spells={20165}},
                    [2313] = {row=3, col=11, maxRank=1, spells={48087}},
                    [2307] = {row=3, col=12, maxRank=1, spells={879}, prereqs={{id=2311, rank=1}}},
                    [2296] = {row=4, col=1, maxRank=1, spells={6940}},
                    [2305] = {row=4, col=2, maxRank=1, spells={10308}},
                    [2290] = {row=4, col=3, maxRank=1, spells={31801}},
                    [2308] = {row=4, col=12, maxRank=1, spells={20473}, prereqs={{id=2307, rank=1}}},
                    [2306] = {row=5, col=2, maxRank=1, spells={31884}},
                    [2309] = {row=5, col=12, maxRank=1, spells={53385}, prereqs={{id=2308, rank=1}}},
                },  -- talents
            },  -- Holy
            [2] = {
                name = "Protection",
                tabId = 382,
                masteryTalentId = 2286,
                talents = {
                    [2286] = {row=1, col=2, maxRank=1, spells={20271}},
                    [2298] = {row=2, col=1, maxRank=1, spells={1038}},
                    [2302] = {row=2, col=2, maxRank=1, spells={26573}},
                    [2291] = {row=2, col=3, maxRank=1, spells={20166}},
                    [2297] = {row=3, col=1, maxRank=1, spells={1044}},
                    [2299] = {row=3, col=2, maxRank=1, spells={642}},
                    [2288] = {row=3, col=3, maxRank=1, spells={20165}},
                    [2296] = {row=4, col=1, maxRank=1, spells={6940}},
                    [2305] = {row=4, col=2, maxRank=1, spells={10308}},
                    [2290] = {row=4, col=3, maxRank=1, spells={31801}},
                    [2306] = {row=5, col=2, maxRank=1, spells={31884}},
                },  -- talents
            },  -- Protection
            [3] = {
                name = "Retribution",
                tabId = 383,
                masteryTalentId = 2286,
                talents = {
                    [2286] = {row=1, col=2, maxRank=1, spells={20271}},
                    [2303] = {row=1, col=12, maxRank=1, spells={24275}},
                    [2298] = {row=2, col=1, maxRank=1, spells={1038}},
                    [2302] = {row=2, col=2, maxRank=1, spells={26573}},
                    [2291] = {row=2, col=3, maxRank=1, spells={20166}},
                    [2297] = {row=3, col=1, maxRank=1, spells={1044}},
                    [2299] = {row=3, col=2, maxRank=1, spells={642}},
                    [2288] = {row=3, col=3, maxRank=1, spells={20165}},
                    [2296] = {row=4, col=1, maxRank=1, spells={6940}},
                    [2305] = {row=4, col=2, maxRank=1, spells={10308}},
                    [2290] = {row=4, col=3, maxRank=1, spells={31801}},
                    [2306] = {row=5, col=2, maxRank=1, spells={31884}},
                },  -- talents
            },  -- Retribution
        },  -- tabs
    },  -- PALADIN

    -- ══ HUNTER (classId=3) ══
    [3] = {
        className = "HUNTER",
        tabs = {
            [1] = {
                name = "Beast Mastery",
                tabId = 361,
                masteryTalentId = 2236,
                talents = {
                    [2236] = {row=1, col=2, maxRank=1, spells={56641}},
                    [2253] = {row=2, col=1, maxRank=1, spells={3044}},
                    [2250] = {row=2, col=2, maxRank=1, spells={2643}},
                    [2241] = {row=2, col=3, maxRank=1, spells={19556}},
                    [2252] = {row=3, col=1, maxRank=1, spells={5384}},
                    [2245] = {row=3, col=2, maxRank=1, spells={19263}},
                    [2239] = {row=3, col=3, maxRank=1, spells={61846}},
                    [2251] = {row=4, col=1, maxRank=1, spells={34490}},
                    [2247] = {row=4, col=2, maxRank=1, spells={19503}},
                    [2238] = {row=4, col=3, maxRank=1, spells={13161}},
                    [2246] = {row=5, col=2, maxRank=1, spells={781}},
                },  -- talents
            },  -- Beast Mastery
            [2] = {
                name = "Marksmanship",
                tabId = 362,
                masteryTalentId = 2244,
                talents = {
                    [2236] = {row=1, col=2, maxRank=1, spells={56641}},
                    [2244] = {row=1, col=4, maxRank=1, spells={53217}, mastery=true},
                    [2254] = {row=1, col=12, maxRank=1, spells={3045}},
                    [2253] = {row=2, col=1, maxRank=1, spells={3044}},
                    [2250] = {row=2, col=2, maxRank=1, spells={2643}},
                    [2241] = {row=2, col=3, maxRank=1, spells={19556}},
                    [2243] = {row=2, col=11, maxRank=1, spells={34499}},
                    [2237] = {row=2, col=12, maxRank=1, spells={3674}},
                    [2242] = {row=2, col=13, maxRank=1, spells={53265}},
                    [2252] = {row=3, col=1, maxRank=1, spells={5384}},
                    [2245] = {row=3, col=2, maxRank=1, spells={19263}},
                    [2239] = {row=3, col=3, maxRank=1, spells={61846}},
                    [2233] = {row=3, col=12, maxRank=1, spells={56344}},
                    [2251] = {row=4, col=1, maxRank=1, spells={34490}},
                    [2247] = {row=4, col=2, maxRank=1, spells={19503}},
                    [2238] = {row=4, col=3, maxRank=1, spells={13161}},
                    [2248] = {row=4, col=12, maxRank=1, spells={53209}},
                    [2246] = {row=5, col=2, maxRank=1, spells={781}},
                    [2249] = {row=5, col=12, maxRank=1, spells={60053}},
                },  -- talents
            },  -- Marksmanship
            [3] = {
                name = "Survival",
                tabId = 363,
                masteryTalentId = 2236,
                talents = {
                    [2236] = {row=1, col=2, maxRank=1, spells={56641}},
                    [2253] = {row=2, col=1, maxRank=1, spells={3044}},
                    [2250] = {row=2, col=2, maxRank=1, spells={2643}},
                    [2241] = {row=2, col=3, maxRank=1, spells={19556}},
                    [2252] = {row=3, col=1, maxRank=1, spells={5384}},
                    [2245] = {row=3, col=2, maxRank=1, spells={19263}},
                    [2239] = {row=3, col=3, maxRank=1, spells={61846}},
                    [2251] = {row=4, col=1, maxRank=1, spells={34490}},
                    [2247] = {row=4, col=2, maxRank=1, spells={19503}},
                    [2238] = {row=4, col=3, maxRank=1, spells={13161}},
                    [2246] = {row=5, col=2, maxRank=1, spells={781}},
                },  -- talents
            },  -- Survival
        },  -- tabs
    },  -- HUNTER

    -- ══ ROGUE (classId=4) ══
    [4] = {
        className = "ROGUE",
        tabs = {
            [1] = {
                name = "Assasination",
                tabId = 181,
                masteryTalentId = 2256,
                talents = {
                    [2262] = {row=1, col=2, maxRank=1, spells={1784}},
                    [2258] = {row=2, col=2, maxRank=1, spells={8643}},
                    [2256] = {row=3, col=2, maxRank=1, spells={1766}},
                    [2260] = {row=4, col=2, maxRank=1, spells={26889}},
                    [2259] = {row=5, col=2, maxRank=1, spells={36554}},
                },  -- talents
            },  -- Assasination
            [2] = {
                name = "Combat",
                tabId = 182,
                masteryTalentId = 2247,
                talents = {
                    [2262] = {row=1, col=2, maxRank=1, spells={1784}},
                    [2257] = {row=1, col=12, maxRank=1, spells={51690}},
                    [2258] = {row=2, col=2, maxRank=1, spells={8643}},
                    [2261] = {row=2, col=12, maxRank=1, spells={51723}},
                    [2256] = {row=3, col=2, maxRank=1, spells={1766}},
                    [2260] = {row=4, col=2, maxRank=1, spells={26889}},
                    [2259] = {row=5, col=2, maxRank=1, spells={36554}},
                    [2263] = {row=5, col=12, maxRank=1, spells={900096}},
                    [2247] = {row=6, col=4, maxRank=1, spells={13852}, mastery=true},
                },  -- talents
            },  -- Combat
            [3] = {
                name = "Subtlety",
                tabId = 183,
                masteryTalentId = 2256,
                talents = {
                    [2262] = {row=1, col=2, maxRank=1, spells={1784}},
                    [2258] = {row=2, col=2, maxRank=1, spells={8643}},
                    [2256] = {row=3, col=2, maxRank=1, spells={1766}},
                    [2260] = {row=4, col=2, maxRank=1, spells={26889}},
                    [2259] = {row=5, col=2, maxRank=1, spells={36554}},
                },  -- talents
            },  -- Subtlety
        },  -- tabs
    },  -- ROGUE

    -- ══ PRIEST (classId=5) ══
    [5] = {
        className = "PRIEST",
        tabs = {
            [1] = {
                name = "Discipline",
                tabId = 201,
                masteryTalentId = 321,
                talents = {
                    [2290] = {row=1, col=2, maxRank=1, spells={589}},
                    [321] = {row=1, col=4, maxRank=2, spells={14531, 14774}, mastery=true},
                    [2291] = {row=2, col=2, maxRank=1, spells={32379}},
                    [2289] = {row=3, col=2, maxRank=1, spells={47585}},
                    [2297] = {row=4, col=2, maxRank=1, spells={15487}},
                    [2280] = {row=5, col=2, maxRank=1, spells={10060}},
                },  -- talents
            },  -- Discipline
            [2] = {
                name = "Holy",
                tabId = 202,
                masteryTalentId = 2280,
                talents = {
                    [2290] = {row=1, col=2, maxRank=1, spells={589}},
                    [2291] = {row=2, col=2, maxRank=1, spells={32379}},
                    [2289] = {row=3, col=2, maxRank=1, spells={47585}},
                    [2297] = {row=4, col=2, maxRank=1, spells={15487}},
                    [2280] = {row=5, col=2, maxRank=1, spells={10060}},
                },  -- talents
            },  -- Holy
            [3] = {
                name = "Shadow",
                tabId = 203,
                masteryTalentId = 2292,
                talents = {
                    [2290] = {row=1, col=2, maxRank=1, spells={589}},
                    [2292] = {row=1, col=4, maxRank=1, spells={15473}, mastery=true},
                    [2296] = {row=1, col=12, maxRank=1, spells={15286}},
                    [2291] = {row=2, col=2, maxRank=1, spells={32379}},
                    [2294] = {row=2, col=12, maxRank=1, spells={15407}},
                    [2289] = {row=3, col=2, maxRank=1, spells={47585}},
                    [2295] = {row=3, col=12, maxRank=1, spells={34914}},
                    [2297] = {row=4, col=2, maxRank=1, spells={15487}},
                    [2293] = {row=4, col=12, maxRank=1, spells={2944}},
                    [2280] = {row=5, col=2, maxRank=1, spells={10060}},
                    [2298] = {row=5, col=12, maxRank=1, spells={900099}},
                },  -- talents
            },  -- Shadow
        },  -- tabs
    },  -- PRIEST

    -- ══ DEATHKNIGHT (classId=6) ══
    [6] = {
        className = "DEATHKNIGHT",
        tabs = {
            [1] = {
                name = "Blood",
                tabId = 398,
                masteryTalentId = 1961,
                talents = {
                    [2292] = {row=1, col=1, maxRank=1, spells={49998}},
                    [2315] = {row=1, col=2, maxRank=1, spells={49998}},
                    [2293] = {row=1, col=3, maxRank=1, spells={56815}, prereqs={{id=2292, rank=1}}},
                    [2320] = {row=1, col=5, maxRank=2, spells={49627, 49628}},
                    [2321] = {row=1, col=7, maxRank=2, spells={49503, 49504}},
                    [2322] = {row=1, col=9, maxRank=2, spells={49787, 49789}},
                    [2291] = {row=1, col=12, maxRank=1, spells={55050}},
                    [2287] = {row=2, col=1, maxRank=1, spells={48263}, prereqs={{id=49998, rank=1}}},
                    [2298] = {row=2, col=2, maxRank=1, spells={50371}},
                    [2288] = {row=2, col=3, maxRank=1, spells={48265}, prereqs={{id=2292, rank=0}}},
                    [2323] = {row=2, col=6, maxRank=3, spells={48978, 49391, 49393}},
                    [2324] = {row=2, col=8, maxRank=2, spells={31228, 31230}},
                    [2304] = {row=2, col=11, maxRank=1, spells={55226}},
                    [2297] = {row=2, col=12, maxRank=1, spells={55233}},
                    [2309] = {row=2, col=13, maxRank=1, spells={50029}},
                    [2299] = {row=3, col=1, maxRank=1, spells={50385}},
                    [2313] = {row=3, col=2, maxRank=1, spells={49509}},
                    [2310] = {row=3, col=3, maxRank=1, spells={50392}, prereqs={{id=2288, rank=0}}},
                    [1961] = {row=3, col=7, maxRank=1, spells={49028}, flags=1, mastery=true},
                    [2305] = {row=3, col=11, maxRank=1, spells={49497}},
                    [2317] = {row=3, col=12, maxRank=1, spells={48707}},
                    [2318] = {row=3, col=13, maxRank=1, spells={49543}},
                    [2296] = {row=4, col=1, maxRank=1, spells={55610}},
                    [2301] = {row=4, col=2, maxRank=1, spells={53138}},
                    [2314] = {row=4, col=3, maxRank=1, spells={46584}},
                    [2312] = {row=4, col=11, maxRank=1, spells={50150}},
                    [2302] = {row=4, col=12, maxRank=1, spells={49005}},
                    [2319] = {row=4, col=13, maxRank=1, spells={61158}},
                    [2300] = {row=5, col=2, maxRank=1, spells={900042}},
                    [2308] = {row=5, col=12, maxRank=1, spells={48982}},
                },  -- talents
            },  -- Blood
            [2] = {
                name = "Frost",
                tabId = 399,
                masteryTalentId = 2287,
                talents = {
                    [2292] = {row=1, col=1, maxRank=1, spells={49998}},
                    [2315] = {row=1, col=2, maxRank=1, spells={49998}},
                    [2293] = {row=1, col=3, maxRank=1, spells={56815}, prereqs={{id=2292, rank=1}}},
                    [2287] = {row=2, col=1, maxRank=1, spells={48263}, prereqs={{id=49998, rank=1}}},
                    [2298] = {row=2, col=2, maxRank=1, spells={50371}},
                    [2288] = {row=2, col=3, maxRank=1, spells={48265}, prereqs={{id=2292, rank=0}}},
                    [2299] = {row=3, col=1, maxRank=1, spells={50385}},
                    [2313] = {row=3, col=2, maxRank=1, spells={49509}},
                    [2310] = {row=3, col=3, maxRank=1, spells={50392}, prereqs={{id=2288, rank=0}}},
                    [2296] = {row=4, col=1, maxRank=1, spells={55610}},
                    [2301] = {row=4, col=2, maxRank=1, spells={53138}},
                    [2314] = {row=4, col=3, maxRank=1, spells={46584}},
                    [2300] = {row=5, col=2, maxRank=1, spells={900042}},
                },  -- talents
            },  -- Frost
            [3] = {
                name = "Unholy",
                tabId = 400,
                masteryTalentId = 2287,
                talents = {
                    [2292] = {row=1, col=1, maxRank=1, spells={49998}},
                    [2315] = {row=1, col=2, maxRank=1, spells={49998}},
                    [2293] = {row=1, col=3, maxRank=1, spells={56815}, prereqs={{id=2292, rank=1}}},
                    [2287] = {row=2, col=1, maxRank=1, spells={48263}, prereqs={{id=49998, rank=1}}},
                    [2298] = {row=2, col=2, maxRank=1, spells={50371}},
                    [2288] = {row=2, col=3, maxRank=1, spells={48265}, prereqs={{id=2292, rank=0}}},
                    [2299] = {row=3, col=1, maxRank=1, spells={50385}},
                    [2313] = {row=3, col=2, maxRank=1, spells={49509}},
                    [2310] = {row=3, col=3, maxRank=1, spells={50392}, prereqs={{id=2288, rank=0}}},
                    [2296] = {row=4, col=1, maxRank=1, spells={55610}},
                    [2301] = {row=4, col=2, maxRank=1, spells={53138}},
                    [2314] = {row=4, col=3, maxRank=1, spells={46584}},
                    [2300] = {row=5, col=2, maxRank=1, spells={900042}},
                },  -- talents
            },  -- Unholy
        },  -- tabs
    },  -- DEATHKNIGHT

    -- ══ SHAMAN (classId=7) ══
    [7] = {
        className = "SHAMAN",
        tabs = {
            [1] = {
                name = "Elemental",
                tabId = 261,
                masteryTalentId = 2308,
                talents = {
                    [2280] = {row=1, col=2, maxRank=1, spells={8056}},
                    [2308] = {row=1, col=4, maxRank=1, spells={29180}, mastery=true},
                    [2300] = {row=2, col=2, maxRank=1, spells={17364}},
                    [2305] = {row=2, col=3, maxRank=1, spells={900091}},
                    [2304] = {row=3, col=2, maxRank=1, spells={51886}},
                    [2306] = {row=3, col=3, maxRank=1, spells={900093}},
                    [2301] = {row=4, col=2, maxRank=1, spells={57994}},
                    [2307] = {row=4, col=3, maxRank=1, spells={900095}},
                    [2302] = {row=5, col=2, maxRank=1, spells={66842}},
                },  -- talents
            },  -- Elemental
            [2] = {
                name = "Enhancement",
                tabId = 262,
                masteryTalentId = 2309,
                talents = {
                    [2280] = {row=1, col=2, maxRank=1, spells={8056}},
                    [2309] = {row=1, col=4, maxRank=1, spells={30819}, mastery=true},
                    [2300] = {row=2, col=2, maxRank=1, spells={17364}},
                    [2305] = {row=2, col=3, maxRank=1, spells={900091}},
                    [2304] = {row=3, col=2, maxRank=1, spells={51886}},
                    [2306] = {row=3, col=3, maxRank=1, spells={900093}},
                    [2301] = {row=4, col=2, maxRank=1, spells={57994}},
                    [2307] = {row=4, col=3, maxRank=1, spells={900095}},
                    [2302] = {row=5, col=2, maxRank=1, spells={66842}},
                },  -- talents
            },  -- Enhancement
            [3] = {
                name = "Restoration",
                tabId = 263,
                masteryTalentId = 2310,
                talents = {
                    [2280] = {row=1, col=2, maxRank=1, spells={8056}},
                    [2310] = {row=1, col=4, maxRank=1, spells={16213}, mastery=true},
                    [2300] = {row=2, col=2, maxRank=1, spells={17364}},
                    [2305] = {row=2, col=3, maxRank=1, spells={900091}},
                    [2304] = {row=3, col=2, maxRank=1, spells={51886}},
                    [2306] = {row=3, col=3, maxRank=1, spells={900093}},
                    [2301] = {row=4, col=2, maxRank=1, spells={57994}},
                    [2307] = {row=4, col=3, maxRank=1, spells={900095}},
                    [2302] = {row=5, col=2, maxRank=1, spells={66842}},
                },  -- talents
            },  -- Restoration
            [4] = {
                name = "Primal Conduit",
                tabId = 10074,
                masteryTalentId = 2272,
                talents = {
                    [2280] = {row=1, col=2, maxRank=1, spells={8056}},
                    [2282] = {row=1, col=12, maxRank=1, spells={900050}},
                    [2300] = {row=2, col=2, maxRank=1, spells={17364}},
                    [2305] = {row=2, col=3, maxRank=1, spells={900091}},
                    [2285] = {row=2, col=11, maxRank=1, spells={20135}},
                    [2276] = {row=2, col=12, maxRank=1, spells={900067}},
                    [2304] = {row=3, col=2, maxRank=1, spells={51886}},
                    [2306] = {row=3, col=3, maxRank=1, spells={900093}},
                    [2287] = {row=3, col=11, maxRank=1, spells={47296}},
                    [2279] = {row=3, col=12, maxRank=1, spells={900066}},
                    [2301] = {row=4, col=2, maxRank=1, spells={57994}},
                    [2307] = {row=4, col=3, maxRank=1, spells={900095}},
                    [2288] = {row=4, col=11, maxRank=1, spells={58874}},
                    [2278] = {row=4, col=12, maxRank=1, spells={900065}},
                    [2302] = {row=5, col=2, maxRank=1, spells={66842}},
                    [2277] = {row=5, col=12, maxRank=1, spells={900064}},
                    [2299] = {row=6, col=12, maxRank=1, spells={900055}},
                    [2296] = {row=7, col=12, maxRank=1, spells={900051}},
                    [2297] = {row=8, col=12, maxRank=1, spells={900052}},
                    [2298] = {row=9, col=12, maxRank=1, spells={900053}},
                    [2274] = {row=10, col=12, maxRank=1, spells={900054}},
                    [2272] = {row=11, col=4, maxRank=1, spells={900045}, mastery=true},
                },  -- talents
            },  -- Primal Conduit
        },  -- tabs
    },  -- SHAMAN

    -- ══ MAGE (classId=8) ══
    [8] = {
        className = "MAGE",
        tabs = {
            [1] = {
                name = "Fire",
                tabId = 41,
                masteryTalentId = 23,
                talents = {
                    [2223] = {row=1, col=2, maxRank=1, spells={66}},
                    [23] = {row=1, col=4, maxRank=1, spells={12848}, mastery=true},
                    [1850] = {row=1, col=12, maxRank=3, spells={44445, 44446, 44448}},
                    [2245] = {row=2, col=1, maxRank=1, spells={12503}},
                    [2224] = {row=2, col=2, maxRank=1, spells={55342}},
                    [2241] = {row=2, col=3, maxRank=1, spells={12577}},
                    [2230] = {row=2, col=12, maxRank=1, spells={11129}},
                    [2244] = {row=3, col=1, maxRank=1, spells={64357}},
                    [2225] = {row=3, col=2, maxRank=1, spells={1953}},
                    [2242] = {row=3, col=3, maxRank=1, spells={31572}},
                    [2239] = {row=3, col=11, maxRank=1, spells={900044}},
                    [2233] = {row=3, col=12, maxRank=1, spells={42926}},
                    [2243] = {row=4, col=1, maxRank=1, spells={31583}},
                    [2228] = {row=4, col=2, maxRank=1, spells={30449}},
                    [2237] = {row=4, col=3, maxRank=1, spells={29076}},
                    [2232] = {row=4, col=12, maxRank=1, spells={42873}},
                    [2234] = {row=5, col=2, maxRank=1, spells={55360}},
                    [2231] = {row=5, col=12, maxRank=1, spells={42891}},
                },  -- talents
            },  -- Fire
            [2] = {
                name = "Frost",
                tabId = 61,
                masteryTalentId = 2223,
                talents = {
                    [2223] = {row=1, col=2, maxRank=1, spells={66}},
                    [2245] = {row=2, col=1, maxRank=1, spells={12503}},
                    [2224] = {row=2, col=2, maxRank=1, spells={55342}},
                    [2241] = {row=2, col=3, maxRank=1, spells={12577}},
                    [2244] = {row=3, col=1, maxRank=1, spells={64357}},
                    [2225] = {row=3, col=2, maxRank=1, spells={1953}},
                    [2242] = {row=3, col=3, maxRank=1, spells={31572}},
                    [2243] = {row=4, col=1, maxRank=1, spells={31583}},
                    [2228] = {row=4, col=2, maxRank=1, spells={30449}},
                    [2237] = {row=4, col=3, maxRank=1, spells={29076}},
                    [2234] = {row=5, col=2, maxRank=1, spells={55360}},
                },  -- talents
            },  -- Frost
            [3] = {
                name = "Arcane",
                tabId = 81,
                masteryTalentId = 2223,
                talents = {
                    [2223] = {row=1, col=2, maxRank=1, spells={66}},
                    [2245] = {row=2, col=1, maxRank=1, spells={12503}},
                    [2224] = {row=2, col=2, maxRank=1, spells={55342}},
                    [2241] = {row=2, col=3, maxRank=1, spells={12577}},
                    [2244] = {row=3, col=1, maxRank=1, spells={64357}},
                    [2225] = {row=3, col=2, maxRank=1, spells={1953}},
                    [2242] = {row=3, col=3, maxRank=1, spells={31572}},
                    [2243] = {row=4, col=1, maxRank=1, spells={31583}},
                    [2228] = {row=4, col=2, maxRank=1, spells={30449}},
                    [2237] = {row=4, col=3, maxRank=1, spells={29076}},
                    [2234] = {row=5, col=2, maxRank=1, spells={55360}},
                },  -- talents
            },  -- Arcane
        },  -- tabs
    },  -- MAGE

    -- ══ WARLOCK (classId=9) ══
    [9] = {
        className = "WARLOCK",
        tabs = {
            [1] = {
                name = "Vengance",
                tabId = 301,
                masteryTalentId = 2263,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                    [2284] = {row=2, col=2, maxRank=1, spells={710}},
                    [2287] = {row=2, col=3, maxRank=1, spells={2362}},
                    [2286] = {row=3, col=3, maxRank=1, spells={6366}},
                    [2285] = {row=4, col=3, maxRank=1, spells={693}},
                },  -- talents
            },  -- Vengance
            [2] = {
                name = "Affliction",
                tabId = 302,
                masteryTalentId = 2263,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                    [2284] = {row=2, col=2, maxRank=1, spells={710}},
                    [2287] = {row=2, col=3, maxRank=1, spells={2362}},
                    [2286] = {row=3, col=3, maxRank=1, spells={6366}},
                    [2285] = {row=4, col=3, maxRank=1, spells={693}},
                },  -- talents
            },  -- Affliction
            [3] = {
                name = "Demonology",
                tabId = 303,
                masteryTalentId = 2273,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                    [1001] = {row=1, col=12, maxRank=1, spells={47241}},
                    [2284] = {row=2, col=2, maxRank=1, spells={710}},
                    [2287] = {row=2, col=3, maxRank=1, spells={2362}},
                    [2266] = {row=2, col=11, maxRank=1, spells={18768}},
                    [2264] = {row=2, col=12, maxRank=1, spells={603}},
                    [2283] = {row=2, col=13, maxRank=1, spells={17803}},
                    [2286] = {row=3, col=3, maxRank=1, spells={6366}},
                    [2265] = {row=3, col=11, maxRank=1, spells={47231}},
                    [2280] = {row=3, col=13, maxRank=1, spells={47247}},
                    [2285] = {row=4, col=3, maxRank=1, spells={693}},
                    [2273] = {row=4, col=6, maxRank=1, spells={47240}, mastery=true},
                    [2267] = {row=4, col=11, maxRank=1, spells={18693}},
                    [2262] = {row=4, col=12, maxRank=1, spells={6353}},
                    [2282] = {row=4, col=13, maxRank=1, spells={59741}},
                    [2272] = {row=5, col=12, maxRank=1, spells={47193}},
                },  -- talents
            },  -- Demonology
            [4] = {
                name = "Destruction",
                tabId = 10094,
                masteryTalentId = 2263,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                    [2284] = {row=2, col=2, maxRank=1, spells={710}},
                    [2287] = {row=2, col=3, maxRank=1, spells={2362}},
                    [2286] = {row=3, col=3, maxRank=1, spells={6366}},
                    [2285] = {row=4, col=3, maxRank=1, spells={693}},
                },  -- talents
            },  -- Destruction
            [5] = {
                name = "Havoc",
                tabId = 10095,
                masteryTalentId = 2263,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                    [2284] = {row=2, col=2, maxRank=1, spells={710}},
                    [2287] = {row=2, col=3, maxRank=1, spells={2362}},
                    [2286] = {row=3, col=3, maxRank=1, spells={6366}},
                    [2285] = {row=4, col=3, maxRank=1, spells={693}},
                },  -- talents
            },  -- Havoc
        },  -- tabs
    },  -- WARLOCK

    -- ══ DRUID (classId=11) ══
    [11] = {
        className = "DRUID",
        tabs = {
            [1] = {
                name = "Astral",
                tabId = 281,
                masteryTalentId = 2269,
                talents = {
                    [2276] = {row=1, col=2, maxRank=1, spells={770}},
                    [2269] = {row=1, col=6, maxRank=1, spells={24858}, mastery=true},
                    [2280] = {row=2, col=2, maxRank=1, spells={33786}},
                    [2273] = {row=3, col=2, maxRank=1, spells={339}},
                    [2275] = {row=3, col=3, maxRank=1, spells={467}},
                    [2277] = {row=4, col=1, maxRank=1, spells={20484}},
                    [2278] = {row=4, col=2, maxRank=1, spells={22812}},
                    [2274] = {row=4, col=3, maxRank=1, spells={1126}},
                },  -- talents
            },  -- Astral
            [2] = {
                name = "Feline",
                tabId = 282,
                masteryTalentId = 2270,
                talents = {
                    [2276] = {row=1, col=2, maxRank=1, spells={770}},
                    [2270] = {row=1, col=6, maxRank=1, spells={768}, mastery=true},
                    [2279] = {row=1, col=12, maxRank=1, spells={9821}},
                    [2280] = {row=2, col=2, maxRank=1, spells={33786}},
                    [2273] = {row=3, col=2, maxRank=1, spells={339}},
                    [2275] = {row=3, col=3, maxRank=1, spells={467}},
                    [2277] = {row=4, col=1, maxRank=1, spells={20484}},
                    [2278] = {row=4, col=2, maxRank=1, spells={22812}},
                    [2274] = {row=4, col=3, maxRank=1, spells={1126}},
                },  -- talents
            },  -- Feline
            [3] = {
                name = "Ancient",
                tabId = 283,
                masteryTalentId = 2271,
                talents = {
                    [2276] = {row=1, col=2, maxRank=1, spells={770}},
                    [2271] = {row=1, col=5, maxRank=1, spells={33891}, mastery=true},
                    [2281] = {row=1, col=12, maxRank=1, spells={18562}},
                    [2280] = {row=2, col=2, maxRank=1, spells={33786}},
                    [2273] = {row=3, col=2, maxRank=1, spells={339}},
                    [2275] = {row=3, col=3, maxRank=1, spells={467}},
                    [2277] = {row=4, col=1, maxRank=1, spells={20484}},
                    [2278] = {row=4, col=2, maxRank=1, spells={22812}},
                    [2274] = {row=4, col=3, maxRank=1, spells={1126}},
                },  -- talents
            },  -- Ancient
            [4] = {
                name = "Bear",
                tabId = 10114,
                masteryTalentId = 2268,
                talents = {
                    [2276] = {row=1, col=2, maxRank=1, spells={770}},
                    [2268] = {row=1, col=5, maxRank=1, spells={9634}, mastery=true},
                    [2280] = {row=2, col=2, maxRank=1, spells={33786}},
                    [2273] = {row=3, col=2, maxRank=1, spells={339}},
                    [2275] = {row=3, col=3, maxRank=1, spells={467}},
                    [2277] = {row=4, col=1, maxRank=1, spells={20484}},
                    [2278] = {row=4, col=2, maxRank=1, spells={22812}},
                    [2274] = {row=4, col=3, maxRank=1, spells={1126}},
                },  -- talents
            },  -- Bear
        },  -- tabs
    },  -- DRUID

}  -- SURREAL_TALENT_TREES
