-- ═══════════════════════════════════════════════════════════════════
-- SurrealActionBarConfig_SSUI.lua  —  Shared action bar loadout + proc rules
-- Auto-generated by SDB Editor  —  DO NOT EDIT MANUALLY
-- Used by both client (SSUI addon) and server (Eluna, optional)
-- ═══════════════════════════════════════════════════════════════════

-- Register with SSUI so this file is sent to clients.
-- Do NOT wrap in if/else — SURREAL_ACTIONBAR_CONFIG must exist on BOTH sides.
local SSUI = SSUI or require("SSUI")
SSUI.AddAddon()

SURREAL_ACTIONBAR_CONFIG = {
    -- ══ Warrior (classId=1) ══
    [1] = {
        className = "Warrior",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Fury",
                slots = {20243, 23881, 12328, 5308, 1680, 46924, 100, 46968, 6552, 0, 0, 0},
                procRules = {
                },
            },  -- Fury
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Warrior

    -- ══ Paladin (classId=2) ══
    [2] = {
        className = "Paladin",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Paladin

    -- ══ Hunter (classId=3) ══
    [3] = {
        className = "Hunter",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Hunter

    -- ══ Rogue (classId=4) ══
    [4] = {
        className = "Rogue",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Rogue

    -- ══ Priest (classId=5) ══
    [5] = {
        className = "Priest",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Priest

    -- ══ Death Knight (classId=6) ══
    [6] = {
        className = "Death Knight",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Death Knight

    -- ══ Shaman (classId=7) ══
    [7] = {
        className = "Shaman",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Primal Conduit",
                slots = {403, 8056, 17364, 900067, 900066, 900064, 900065, 51886, 57994, 331, 0, 66842},
                procRules = {
                    { watchBuffSpellId=900049, slot=2, swapIconName="Spell_Nature_EarthShock", enabled=true },
                    { watchBuffSpellId=900048, slot=2, swapIconName="Spell_Frost_FrostShock", enabled=true },
                    { watchBuffSpellId=900047, slot=2, swapIconName="Ability_Skyreach_Wind_Wall", enabled=true },
                    { watchBuffSpellId=900046, slot=2, swapIconName="Spell_Fire_FlameShock", enabled=true },
                    { watchBuffSpellId=900049, slot=1, swapIconName="Spell_Sandbolt", enabled=true },
                    { watchBuffSpellId=900048, slot=1, swapIconName="INV_Elemental_Crystal_Water", enabled=true },
                    { watchBuffSpellId=900047, slot=1, swapIconName="Spell_Nature_ChainLightning", enabled=true },
                    { watchBuffSpellId=900046, slot=1, swapIconName="Spell_Shaman_LavaBurst", enabled=true },
                },
            },  -- Primal Conduit
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Shaman

    -- ══ Mage (classId=8) ══
    [8] = {
        className = "Mage",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Mage

    -- ══ Warlock (classId=9) ══
    [9] = {
        className = "Warlock",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Warlock

    -- ══ Druid (classId=11) ══
    [11] = {
        className = "Druid",
        specs = {
            [1] = {
                name = "Spec 1",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 1
            [2] = {
                name = "Spec 2",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 2
            [3] = {
                name = "Spec 3",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 3
            [4] = {
                name = "Spec 4",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 4
            [5] = {
                name = "Spec 5",
                slots = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                procRules = {
                },
            },  -- Spec 5
        },  -- specs
    },  -- Druid

}  -- SURREAL_ACTIONBAR_CONFIG
