-- ═══════════════════════════════════════════════════════════════════
-- SurrealTalentConfig_AIO.lua  —  Shared talent tree definitions
-- Auto-generated by SDB Editor  —  DO NOT EDIT MANUALLY
-- Used by both client (AIO addon) and server (Eluna validation)
-- ═══════════════════════════════════════════════════════════════════

-- Register with AIO so this file is sent to clients.
-- Do NOT wrap in if/else — SURREAL_TALENT_TREES must exist on BOTH sides.
local AIO = AIO or require("AIO")
AIO.AddAddon()

SURREAL_TALENT_TREES = {
    -- ══ WARRIOR (classId=1) ══
    [1] = {
        className = "WARRIOR",
        tabs = {
            [1] = {
                name = "Arms",
                tabId = 161,
                masteryTalentId = 2284,
                talents = {
                    [2284] = {row=1, col=1, maxRank=1, spells={674}},
                    [2305] = {row=1, col=2, maxRank=1, spells={100}},
                    [2286] = {row=2, col=1, maxRank=1, spells={29725}},
                    [2294] = {row=2, col=2, maxRank=1, spells={5308}},
                    [2287] = {row=3, col=1, maxRank=1, spells={674}},
                    [2309] = {row=3, col=2, maxRank=1, spells={46968}},
                    [2310] = {row=4, col=1, maxRank=1, spells={46917}},
                    [2308] = {row=4, col=2, maxRank=1, spells={6552}},
                    [2290] = {row=5, col=2, maxRank=1, spells={46924}},
                },  -- talents
            },  -- Arms
            [2] = {
                name = "Fury",
                tabId = 164,
                masteryTalentId = 154,
                talents = {
                    [2284] = {row=1, col=1, maxRank=1, spells={674}},
                    [2305] = {row=1, col=2, maxRank=1, spells={100}},
                    [154] = {row=1, col=4, maxRank=1, spells={29801}, mastery=true},
                    [2289] = {row=1, col=12, maxRank=1, spells={23881}},
                    [2286] = {row=2, col=1, maxRank=1, spells={29725}},
                    [2294] = {row=2, col=2, maxRank=1, spells={5308}},
                    [2296] = {row=2, col=11, maxRank=1, spells={12867}},
                    [2293] = {row=2, col=12, maxRank=1, spells={56924}},
                    [2287] = {row=3, col=1, maxRank=1, spells={674}},
                    [2309] = {row=3, col=2, maxRank=1, spells={46968}},
                    [2297] = {row=3, col=11, maxRank=1, spells={56614}},
                    [2298] = {row=3, col=12, maxRank=1, spells={20243}},
                    [2310] = {row=4, col=1, maxRank=1, spells={46917}},
                    [2308] = {row=4, col=2, maxRank=1, spells={6552}},
                    [2304] = {row=4, col=11, maxRank=1, spells={50687}},
                    [2299] = {row=4, col=12, maxRank=1, spells={12328}},
                    [2290] = {row=5, col=2, maxRank=1, spells={46924}},
                    [2295] = {row=5, col=12, maxRank=1, spells={1680}},
                },  -- talents
            },  -- Fury
            [3] = {
                name = "Protection",
                tabId = 163,
                masteryTalentId = 138,
                talents = {
                    [2284] = {row=1, col=1, maxRank=1, spells={674}},
                    [2305] = {row=1, col=2, maxRank=1, spells={100}},
                    [140] = {row=1, col=4, maxRank=5, spells={12299, 12761, 12762, 12763, 12764}},
                    [142] = {row=1, col=4, maxRank=2, spells={12301, 12818}},
                    [150] = {row=1, col=4, maxRank=2, spells={12312, 12803}},
                    [153] = {row=1, col=4, maxRank=1, spells={12975}, flags=1},
                    [1652] = {row=1, col=4, maxRank=2, spells={29593, 29594}},
                    [2236] = {row=1, col=4, maxRank=1, spells={57499}},
                    [2247] = {row=1, col=4, maxRank=2, spells={59088, 59089}},
                    [144] = {row=1, col=5, maxRank=3, spells={50685, 50686, 50687}},
                    [147] = {row=1, col=5, maxRank=2, spells={12797, 12799}},
                    [148] = {row=1, col=5, maxRank=1, spells={50720}, prereqs={{id=152, rank=0}}, flags=1},
                    [151] = {row=1, col=5, maxRank=2, spells={12313, 12804}},
                    [152] = {row=1, col=5, maxRank=1, spells={12809}, flags=1},
                    [1601] = {row=1, col=5, maxRank=5, spells={12298, 12724, 12725, 12726, 12727}},
                    [1653] = {row=1, col=5, maxRank=3, spells={29140, 29143, 29144}},
                    [1666] = {row=1, col=5, maxRank=1, spells={20243}, flags=1},
                    [1871] = {row=1, col=5, maxRank=3, spells={46951, 46952, 46953}, prereqs={{id=1666, rank=0}}},
                    [1872] = {row=1, col=5, maxRank=1, spells={46968}, flags=1},
                    [138] = {row=1, col=6, maxRank=5, spells={12297, 12750, 12751, 12752, 12753}, mastery=true},
                    [141] = {row=1, col=6, maxRank=3, spells={12287, 12665, 12666}},
                    [146] = {row=1, col=6, maxRank=3, spells={12308, 12810, 12811}},
                    [149] = {row=1, col=6, maxRank=2, spells={12311, 12958}},
                    [702] = {row=1, col=6, maxRank=5, spells={16538, 16539, 16540, 16541, 16542}},
                    [1654] = {row=1, col=6, maxRank=2, spells={29598, 29599}},
                    [1660] = {row=1, col=6, maxRank=3, spells={29787, 29790, 29792}},
                    [1870] = {row=1, col=6, maxRank=2, spells={46945, 46949}},
                    [1893] = {row=1, col=6, maxRank=3, spells={47294, 47295, 47296}},
                    [2246] = {row=1, col=6, maxRank=2, spells={58872, 58874}},
                    [2286] = {row=2, col=1, maxRank=1, spells={29725}},
                    [2294] = {row=2, col=2, maxRank=1, spells={5308}},
                    [2287] = {row=3, col=1, maxRank=1, spells={674}},
                    [2309] = {row=3, col=2, maxRank=1, spells={46968}},
                    [2310] = {row=4, col=1, maxRank=1, spells={46917}},
                    [2308] = {row=4, col=2, maxRank=1, spells={6552}},
                    [2290] = {row=5, col=2, maxRank=1, spells={46924}},
                },  -- talents
            },  -- Protection
        },  -- tabs
    },  -- WARRIOR

    -- ══ PALADIN (classId=2) ══
    [2] = {
        className = "PALADIN",
        tabs = {
            [1] = {
                name = "Holy",
                tabId = 381,
                masteryTalentId = 2304,
                talents = {
                    [2286] = {row=1, col=2, maxRank=1, spells={20271}},
                    [2304] = {row=1, col=4, maxRank=1, spells={53563}, mastery=true},
                    [2310] = {row=1, col=12, maxRank=1, spells={54155}},
                    [2298] = {row=2, col=1, maxRank=1, spells={1038}},
                    [2302] = {row=2, col=2, maxRank=1, spells={26573}},
                    [2291] = {row=2, col=3, maxRank=1, spells={20166}},
                    [2312] = {row=2, col=11, maxRank=1, spells={47515}},
                    [2311] = {row=2, col=12, maxRank=1, spells={53592}, prereqs={{id=2310, rank=1}}},
                    [2297] = {row=3, col=1, maxRank=1, spells={1044}},
                    [2299] = {row=3, col=2, maxRank=1, spells={642}},
                    [2288] = {row=3, col=3, maxRank=1, spells={20165}},
                    [2313] = {row=3, col=11, maxRank=1, spells={48087}},
                    [2307] = {row=3, col=12, maxRank=1, spells={879}, prereqs={{id=2311, rank=1}}},
                    [2296] = {row=4, col=1, maxRank=1, spells={6940}},
                    [2305] = {row=4, col=2, maxRank=1, spells={10308}},
                    [2290] = {row=4, col=3, maxRank=1, spells={31801}},
                    [2308] = {row=4, col=12, maxRank=1, spells={20473}, prereqs={{id=2307, rank=1}}},
                    [2306] = {row=5, col=2, maxRank=1, spells={31884}},
                    [2309] = {row=5, col=12, maxRank=1, spells={53385}, prereqs={{id=2308, rank=1}}},
                },  -- talents
            },  -- Holy
            [2] = {
                name = "Protection",
                tabId = 382,
                masteryTalentId = 2286,
                talents = {
                    [2286] = {row=1, col=2, maxRank=1, spells={20271}},
                    [2298] = {row=2, col=1, maxRank=1, spells={1038}},
                    [2302] = {row=2, col=2, maxRank=1, spells={26573}},
                    [2291] = {row=2, col=3, maxRank=1, spells={20166}},
                    [2297] = {row=3, col=1, maxRank=1, spells={1044}},
                    [2299] = {row=3, col=2, maxRank=1, spells={642}},
                    [2288] = {row=3, col=3, maxRank=1, spells={20165}},
                    [2296] = {row=4, col=1, maxRank=1, spells={6940}},
                    [2305] = {row=4, col=2, maxRank=1, spells={10308}},
                    [2290] = {row=4, col=3, maxRank=1, spells={31801}},
                    [2306] = {row=5, col=2, maxRank=1, spells={31884}},
                },  -- talents
            },  -- Protection
            [3] = {
                name = "Retribution",
                tabId = 383,
                masteryTalentId = 2286,
                talents = {
                    [2286] = {row=1, col=2, maxRank=1, spells={20271}},
                    [2303] = {row=1, col=12, maxRank=1, spells={24275}},
                    [2298] = {row=2, col=1, maxRank=1, spells={1038}},
                    [2302] = {row=2, col=2, maxRank=1, spells={26573}},
                    [2291] = {row=2, col=3, maxRank=1, spells={20166}},
                    [2297] = {row=3, col=1, maxRank=1, spells={1044}},
                    [2299] = {row=3, col=2, maxRank=1, spells={642}},
                    [2288] = {row=3, col=3, maxRank=1, spells={20165}},
                    [2296] = {row=4, col=1, maxRank=1, spells={6940}},
                    [2305] = {row=4, col=2, maxRank=1, spells={10308}},
                    [2290] = {row=4, col=3, maxRank=1, spells={31801}},
                    [2306] = {row=5, col=2, maxRank=1, spells={31884}},
                },  -- talents
            },  -- Retribution
        },  -- tabs
    },  -- PALADIN

    -- ══ HUNTER (classId=3) ══
    [3] = {
        className = "HUNTER",
        tabs = {
            [1] = {
                name = "Beast Mastery",
                tabId = 361,
                masteryTalentId = 2236,
                talents = {
                    [2236] = {row=1, col=2, maxRank=1, spells={56641}},
                    [2253] = {row=2, col=1, maxRank=1, spells={3044}},
                    [2250] = {row=2, col=2, maxRank=1, spells={2643}},
                    [2241] = {row=2, col=3, maxRank=1, spells={19556}},
                    [2252] = {row=3, col=1, maxRank=1, spells={5384}},
                    [2245] = {row=3, col=2, maxRank=1, spells={19263}},
                    [2239] = {row=3, col=3, maxRank=1, spells={61846}},
                    [2251] = {row=4, col=1, maxRank=1, spells={34490}},
                    [2247] = {row=4, col=2, maxRank=1, spells={19503}},
                    [2238] = {row=4, col=3, maxRank=1, spells={13161}},
                    [2246] = {row=5, col=2, maxRank=1, spells={781}},
                },  -- talents
            },  -- Beast Mastery
            [2] = {
                name = "Marksmanship",
                tabId = 362,
                masteryTalentId = 2244,
                talents = {
                    [2236] = {row=1, col=2, maxRank=1, spells={56641}},
                    [2244] = {row=1, col=4, maxRank=1, spells={53217}, mastery=true},
                    [2254] = {row=1, col=12, maxRank=1, spells={3045}},
                    [2253] = {row=2, col=1, maxRank=1, spells={3044}},
                    [2250] = {row=2, col=2, maxRank=1, spells={2643}},
                    [2241] = {row=2, col=3, maxRank=1, spells={19556}},
                    [2243] = {row=2, col=11, maxRank=1, spells={34499}},
                    [2237] = {row=2, col=12, maxRank=1, spells={3674}},
                    [2242] = {row=2, col=13, maxRank=1, spells={53265}},
                    [2252] = {row=3, col=1, maxRank=1, spells={5384}},
                    [2245] = {row=3, col=2, maxRank=1, spells={19263}},
                    [2239] = {row=3, col=3, maxRank=1, spells={61846}},
                    [2233] = {row=3, col=12, maxRank=1, spells={56344}},
                    [2251] = {row=4, col=1, maxRank=1, spells={34490}},
                    [2247] = {row=4, col=2, maxRank=1, spells={19503}},
                    [2238] = {row=4, col=3, maxRank=1, spells={13161}},
                    [2248] = {row=4, col=12, maxRank=1, spells={53209}},
                    [2246] = {row=5, col=2, maxRank=1, spells={781}},
                    [2249] = {row=5, col=12, maxRank=1, spells={60053}},
                },  -- talents
            },  -- Marksmanship
            [3] = {
                name = "Survival",
                tabId = 363,
                masteryTalentId = 2236,
                talents = {
                    [2236] = {row=1, col=2, maxRank=1, spells={56641}},
                    [2253] = {row=2, col=1, maxRank=1, spells={3044}},
                    [2250] = {row=2, col=2, maxRank=1, spells={2643}},
                    [2241] = {row=2, col=3, maxRank=1, spells={19556}},
                    [2252] = {row=3, col=1, maxRank=1, spells={5384}},
                    [2245] = {row=3, col=2, maxRank=1, spells={19263}},
                    [2239] = {row=3, col=3, maxRank=1, spells={61846}},
                    [2251] = {row=4, col=1, maxRank=1, spells={34490}},
                    [2247] = {row=4, col=2, maxRank=1, spells={19503}},
                    [2238] = {row=4, col=3, maxRank=1, spells={13161}},
                    [2246] = {row=5, col=2, maxRank=1, spells={781}},
                },  -- talents
            },  -- Survival
        },  -- tabs
    },  -- HUNTER

    -- ══ ROGUE (classId=4) ══
    [4] = {
        className = "ROGUE",
        tabs = {
            [1] = {
                name = "Assasination",
                tabId = 181,
                masteryTalentId = 2250,
                talents = {
                    [2251] = {row=2, col=1, maxRank=1, spells={14195}},
                    [2255] = {row=3, col=1, maxRank=1, spells={51701}},
                    [2250] = {row=4, col=1, maxRank=1, spells={58425}},
                    [2254] = {row=4, col=3, maxRank=1, spells={31230}},
                },  -- talents
            },  -- Assasination
            [2] = {
                name = "Combat",
                tabId = 182,
                masteryTalentId = 2247,
                talents = {
                    [2253] = {row=1, col=12, maxRank=1, spells={61331}},
                    [2251] = {row=2, col=1, maxRank=1, spells={14195}},
                    [2245] = {row=2, col=11, maxRank=1, spells={35553}},
                    [2246] = {row=2, col=13, maxRank=1, spells={51669}},
                    [2255] = {row=3, col=1, maxRank=1, spells={51701}},
                    [2249] = {row=3, col=11, maxRank=1, spells={14137}},
                    [2248] = {row=3, col=13, maxRank=1, spells={14117}},
                    [2250] = {row=4, col=1, maxRank=1, spells={58425}},
                    [2254] = {row=4, col=3, maxRank=1, spells={31230}},
                    [2252] = {row=4, col=11, maxRank=1, spells={51712}},
                    [2247] = {row=6, col=4, maxRank=1, spells={13852}, mastery=true},
                },  -- talents
            },  -- Combat
            [3] = {
                name = "Subtlety",
                tabId = 183,
                masteryTalentId = 2250,
                talents = {
                    [2251] = {row=2, col=1, maxRank=1, spells={14195}},
                    [2255] = {row=3, col=1, maxRank=1, spells={51701}},
                    [2250] = {row=4, col=1, maxRank=1, spells={58425}},
                    [2254] = {row=4, col=3, maxRank=1, spells={31230}},
                },  -- talents
            },  -- Subtlety
        },  -- tabs
    },  -- ROGUE

    -- ══ PRIEST (classId=5) ══
    [5] = {
        className = "PRIEST",
        tabs = {
            [1] = {
                name = "Discipline",
                tabId = 201,
                masteryTalentId = 321,
                talents = {
                    [2290] = {row=1, col=2, maxRank=1, spells={589}},
                    [321] = {row=1, col=4, maxRank=2, spells={14531, 14774}, mastery=true},
                    [2291] = {row=2, col=2, maxRank=1, spells={32379}},
                    [2289] = {row=3, col=2, maxRank=1, spells={47585}},
                    [2297] = {row=4, col=2, maxRank=1, spells={15487}},
                    [2280] = {row=5, col=2, maxRank=1, spells={10060}},
                },  -- talents
            },  -- Discipline
            [2] = {
                name = "Holy",
                tabId = 202,
                masteryTalentId = 2280,
                talents = {
                    [2290] = {row=1, col=2, maxRank=1, spells={589}},
                    [2291] = {row=2, col=2, maxRank=1, spells={32379}},
                    [2289] = {row=3, col=2, maxRank=1, spells={47585}},
                    [2297] = {row=4, col=2, maxRank=1, spells={15487}},
                    [2280] = {row=5, col=2, maxRank=1, spells={10060}},
                },  -- talents
            },  -- Holy
            [3] = {
                name = "Shadow",
                tabId = 203,
                masteryTalentId = 2292,
                talents = {
                    [2290] = {row=1, col=2, maxRank=1, spells={589}},
                    [2292] = {row=1, col=4, maxRank=1, spells={15473}, mastery=true},
                    [2296] = {row=1, col=12, maxRank=1, spells={15286}},
                    [2291] = {row=2, col=2, maxRank=1, spells={32379}},
                    [2294] = {row=2, col=12, maxRank=1, spells={15407}},
                    [2289] = {row=3, col=2, maxRank=1, spells={47585}},
                    [2295] = {row=3, col=12, maxRank=1, spells={34914}},
                    [2297] = {row=4, col=2, maxRank=1, spells={15487}},
                    [2293] = {row=4, col=12, maxRank=1, spells={2944}},
                    [2280] = {row=5, col=2, maxRank=1, spells={10060}},
                },  -- talents
            },  -- Shadow
        },  -- tabs
    },  -- PRIEST

    -- ══ DEATHKNIGHT (classId=6) ══
    [6] = {
        className = "DEATHKNIGHT",
        tabs = {
            [1] = {
                name = "Blood",
                tabId = 398,
                masteryTalentId = 1961,
                talents = {
                    [2292] = {row=1, col=1, maxRank=1, spells={49998}},
                    [2315] = {row=1, col=2, maxRank=1, spells={49998}},
                    [2293] = {row=1, col=3, maxRank=1, spells={56815}, prereqs={{id=2292, rank=1}}},
                    [2320] = {row=1, col=5, maxRank=2, spells={49627, 49628}},
                    [2321] = {row=1, col=7, maxRank=2, spells={49503, 49504}},
                    [2322] = {row=1, col=9, maxRank=2, spells={49787, 49789}},
                    [2291] = {row=1, col=12, maxRank=1, spells={55050}},
                    [2287] = {row=2, col=1, maxRank=1, spells={48263}, prereqs={{id=49998, rank=1}}},
                    [2298] = {row=2, col=2, maxRank=1, spells={50371}},
                    [2288] = {row=2, col=3, maxRank=1, spells={48265}, prereqs={{id=2292, rank=0}}},
                    [2323] = {row=2, col=6, maxRank=3, spells={48978, 49391, 49393}},
                    [2324] = {row=2, col=8, maxRank=2, spells={31228, 31230}},
                    [2304] = {row=2, col=11, maxRank=1, spells={55226}},
                    [2297] = {row=2, col=12, maxRank=1, spells={55233}},
                    [2309] = {row=2, col=13, maxRank=1, spells={50029}},
                    [2299] = {row=3, col=1, maxRank=1, spells={50385}},
                    [2313] = {row=3, col=2, maxRank=1, spells={49509}},
                    [2310] = {row=3, col=3, maxRank=1, spells={50392}, prereqs={{id=2288, rank=0}}},
                    [1961] = {row=3, col=7, maxRank=1, spells={49028}, flags=1, mastery=true},
                    [2305] = {row=3, col=11, maxRank=1, spells={49497}},
                    [2317] = {row=3, col=12, maxRank=1, spells={48707}},
                    [2318] = {row=3, col=13, maxRank=1, spells={49543}},
                    [2296] = {row=4, col=1, maxRank=1, spells={55610}},
                    [2301] = {row=4, col=2, maxRank=1, spells={53138}},
                    [2314] = {row=4, col=3, maxRank=1, spells={46584}},
                    [2312] = {row=4, col=11, maxRank=1, spells={50150}},
                    [2302] = {row=4, col=12, maxRank=1, spells={49005}},
                    [2319] = {row=4, col=13, maxRank=1, spells={61158}},
                    [2300] = {row=5, col=2, maxRank=1, spells={900042}},
                    [2308] = {row=5, col=12, maxRank=1, spells={48982}},
                },  -- talents
            },  -- Blood
            [2] = {
                name = "Frost",
                tabId = 399,
                masteryTalentId = 1968,
                talents = {
                    [2292] = {row=1, col=1, maxRank=1, spells={49998}},
                    [2315] = {row=1, col=2, maxRank=1, spells={49998}},
                    [2293] = {row=1, col=3, maxRank=1, spells={56815}, prereqs={{id=2292, rank=1}}},
                    [1971] = {row=1, col=4, maxRank=2, spells={49137, 49657}},
                    [1980] = {row=1, col=5, maxRank=1, spells={49796}, flags=1},
                    [1997] = {row=1, col=6, maxRank=3, spells={49200, 50151, 50152}},
                    [2022] = {row=1, col=7, maxRank=3, spells={49226, 50137, 50138}},
                    [2031] = {row=1, col=8, maxRank=3, spells={49175, 50031, 51456}},
                    [2042] = {row=1, col=9, maxRank=5, spells={50880, 50884, 50885, 50886, 50887}, prereqs={{id=2031, rank=2}}},
                    [2223] = {row=1, col=10, maxRank=1, spells={55610}, prereqs={{id=2042, rank=4}}},
                    [2287] = {row=2, col=1, maxRank=1, spells={48263}, prereqs={{id=49998, rank=1}}},
                    [2298] = {row=2, col=2, maxRank=1, spells={50371}},
                    [2288] = {row=2, col=3, maxRank=1, spells={48265}, prereqs={{id=2292, rank=0}}},
                    [2260] = {row=2, col=4, maxRank=3, spells={50040, 50041, 50043}},
                    [2284] = {row=2, col=5, maxRank=3, spells={65661, 66191, 66192}},
                    [1975] = {row=2, col=6, maxRank=1, spells={49143}, flags=1},
                    [1989] = {row=2, col=7, maxRank=1, spells={49184}, flags=1},
                    [1990] = {row=2, col=8, maxRank=3, spells={49186, 51108, 51109}},
                    [1993] = {row=2, col=9, maxRank=2, spells={49024, 49538}, prereqs={{id=1994, rank=0}}},
                    [1998] = {row=2, col=10, maxRank=5, spells={49202, 50127, 50128, 50129, 50130}},
                    [2299] = {row=3, col=1, maxRank=1, spells={50385}},
                    [2313] = {row=3, col=2, maxRank=1, spells={49509}},
                    [2310] = {row=3, col=3, maxRank=1, spells={50392}, prereqs={{id=2288, rank=0}}},
                    [1999] = {row=3, col=4, maxRank=1, spells={49203}, flags=1},
                    [2020] = {row=3, col=5, maxRank=2, spells={49455, 50147}},
                    [2035] = {row=3, col=6, maxRank=2, spells={55061, 55062}},
                    [2044] = {row=3, col=7, maxRank=5, spells={51123, 51127, 51128, 51129, 51130}},
                    [2210] = {row=3, col=8, maxRank=3, spells={54639, 54638, 54637}},
                    [2215] = {row=3, col=9, maxRank=1, spells={49039}, flags=1},
                    [1968] = {row=3, col=10, maxRank=1, spells={66192}, mastery=true},
                    [2296] = {row=4, col=1, maxRank=1, spells={55610}},
                    [2301] = {row=4, col=2, maxRank=1, spells={53138}},
                    [2314] = {row=4, col=3, maxRank=1, spells={46584}},
                    [1973] = {row=4, col=4, maxRank=5, spells={49140, 49661, 49662, 49663, 49664}},
                    [1979] = {row=4, col=5, maxRank=1, spells={51271}, flags=1},
                    [1981] = {row=4, col=6, maxRank=2, spells={49149, 50115}},
                    [1992] = {row=4, col=7, maxRank=3, spells={49188, 56822, 59057}},
                    [2029] = {row=4, col=8, maxRank=2, spells={50384, 50385}},
                    [2030] = {row=4, col=9, maxRank=3, spells={49471, 49790, 49791}},
                    [2040] = {row=4, col=10, maxRank=3, spells={50187, 50190, 50191}},
                    [2300] = {row=5, col=2, maxRank=1, spells={900042}},
                    [2048] = {row=5, col=4, maxRank=3, spells={51468, 51472, 51473}},
                },  -- talents
            },  -- Frost
            [3] = {
                name = "Unholy",
                tabId = 400,
                masteryTalentId = 2316,
                talents = {
                    [2292] = {row=1, col=1, maxRank=1, spells={49998}},
                    [2315] = {row=1, col=2, maxRank=1, spells={49998}},
                    [2293] = {row=1, col=3, maxRank=1, spells={56815}, prereqs={{id=2292, rank=1}}},
                    [1934] = {row=1, col=4, maxRank=3, spells={48965, 49571, 49572}},
                    [1963] = {row=1, col=5, maxRank=2, spells={49036, 49562}},
                    [1984] = {row=1, col=6, maxRank=1, spells={52143}, prereqs={{id=2225, rank=1}}},
                    [1996] = {row=1, col=7, maxRank=1, spells={49194}, flags=1},
                    [2003] = {row=1, col=8, maxRank=3, spells={49217, 49654, 49655}},
                    [2008] = {row=1, col=9, maxRank=3, spells={49013, 55236, 55237}},
                    [2082] = {row=1, col=10, maxRank=2, spells={51745, 51746}},
                    [2287] = {row=2, col=1, maxRank=1, spells={48263}, prereqs={{id=49998, rank=1}}},
                    [2298] = {row=2, col=2, maxRank=1, spells={50371}},
                    [2288] = {row=2, col=3, maxRank=1, spells={48265}, prereqs={{id=2292, rank=0}}},
                    [2085] = {row=2, col=4, maxRank=1, spells={63560}, prereqs={{id=1984, rank=0}}, flags=1},
                    [2225] = {row=2, col=5, maxRank=2, spells={55620, 55623}},
                    [2226] = {row=2, col=6, maxRank=2, spells={55666, 55667}},
                    [2285] = {row=2, col=7, maxRank=5, spells={66799, 66814, 66815, 66816, 66817}},
                    [1933] = {row=2, col=9, maxRank=3, spells={48963, 49564, 49565}},
                    [1962] = {row=2, col=10, maxRank=3, spells={49032, 49631, 49632}},
                    [2299] = {row=3, col=1, maxRank=1, spells={50385}},
                    [2313] = {row=3, col=2, maxRank=1, spells={49509}},
                    [2310] = {row=3, col=3, maxRank=1, spells={50392}, prereqs={{id=2288, rank=0}}},
                    [2000] = {row=3, col=4, maxRank=1, spells={49206}, flags=1},
                    [2005] = {row=3, col=5, maxRank=5, spells={49220, 49633, 49635, 49636, 49638}},
                    [2009] = {row=3, col=6, maxRank=3, spells={49224, 49610, 49611}},
                    [2036] = {row=3, col=7, maxRank=5, spells={50117, 50118, 50119, 50120, 50121}},
                    [2039] = {row=3, col=8, maxRank=2, spells={49146, 51267}},
                    [2043] = {row=3, col=9, maxRank=3, spells={51099, 51160, 51161}, prereqs={{id=1962, rank=2}}},
                    [2047] = {row=3, col=10, maxRank=5, spells={51459, 51462, 51463, 51464, 51465}},
                    [2296] = {row=4, col=1, maxRank=1, spells={55610}},
                    [2301] = {row=4, col=2, maxRank=1, spells={53138}},
                    [2314] = {row=4, col=3, maxRank=1, spells={46584}},
                    [2221] = {row=4, col=4, maxRank=1, spells={51052}, prereqs={{id=2009, rank=2}}, flags=1},
                    [1985] = {row=4, col=5, maxRank=1, spells={49158}, flags=1},
                    [2001] = {row=4, col=6, maxRank=3, spells={49208, 56834, 56835}},
                    [2004] = {row=4, col=7, maxRank=3, spells={49219, 49627, 49628}},
                    [2007] = {row=4, col=8, maxRank=1, spells={49222}, flags=1},
                    [2011] = {row=4, col=9, maxRank=2, spells={49223, 49599}},
                    [2013] = {row=4, col=10, maxRank=2, spells={50391, 50392}},
                    [2300] = {row=5, col=2, maxRank=1, spells={900042}},
                    [2025] = {row=5, col=4, maxRank=2, spells={49588, 49589}},
                    [2216] = {row=5, col=5, maxRank=1, spells={55090}, flags=1},
                    [2218] = {row=5, col=6, maxRank=5, spells={55129, 55130, 55131, 55132, 55133}},
                    [2316] = {row=5, col=10, maxRank=1, spells={52143}, mastery=true},
                },  -- talents
            },  -- Unholy
        },  -- tabs
    },  -- DEATHKNIGHT

    -- ══ SHAMAN (classId=7) ══
    [7] = {
        className = "SHAMAN",
        tabs = {
            [1] = {
                name = "Elemental",
                tabId = 261,
                masteryTalentId = 2280,
                talents = {
                    [2280] = {row=1, col=2, maxRank=1, spells={8056}},
                    [2300] = {row=2, col=2, maxRank=1, spells={17364}},
                    [2305] = {row=2, col=3, maxRank=1, spells={900091}},
                    [2304] = {row=3, col=2, maxRank=1, spells={51886}},
                    [2306] = {row=3, col=3, maxRank=1, spells={900093}},
                    [2301] = {row=4, col=2, maxRank=1, spells={57994}},
                    [2307] = {row=4, col=3, maxRank=1, spells={900095}},
                    [2302] = {row=5, col=2, maxRank=1, spells={66842}},
                },  -- talents
            },  -- Elemental
            [2] = {
                name = "Enhancement",
                tabId = 262,
                masteryTalentId = 2280,
                talents = {
                    [2280] = {row=1, col=2, maxRank=1, spells={8056}},
                    [2300] = {row=2, col=2, maxRank=1, spells={17364}},
                    [2305] = {row=2, col=3, maxRank=1, spells={900091}},
                    [2304] = {row=3, col=2, maxRank=1, spells={51886}},
                    [2306] = {row=3, col=3, maxRank=1, spells={900093}},
                    [2301] = {row=4, col=2, maxRank=1, spells={57994}},
                    [2307] = {row=4, col=3, maxRank=1, spells={900095}},
                    [2302] = {row=5, col=2, maxRank=1, spells={66842}},
                },  -- talents
            },  -- Enhancement
            [3] = {
                name = "Restoration",
                tabId = 263,
                masteryTalentId = 2280,
                talents = {
                    [2280] = {row=1, col=2, maxRank=1, spells={8056}},
                    [2300] = {row=2, col=2, maxRank=1, spells={17364}},
                    [2305] = {row=2, col=3, maxRank=1, spells={900091}},
                    [2304] = {row=3, col=2, maxRank=1, spells={51886}},
                    [2306] = {row=3, col=3, maxRank=1, spells={900093}},
                    [2301] = {row=4, col=2, maxRank=1, spells={57994}},
                    [2307] = {row=4, col=3, maxRank=1, spells={900095}},
                    [2302] = {row=5, col=2, maxRank=1, spells={66842}},
                },  -- talents
            },  -- Restoration
            [4] = {
                name = "Primal Conduit",
                tabId = 10074,
                masteryTalentId = 2272,
                talents = {
                    [2280] = {row=1, col=2, maxRank=1, spells={8056}},
                    [2282] = {row=1, col=12, maxRank=1, spells={900050}},
                    [2300] = {row=2, col=2, maxRank=1, spells={17364}},
                    [2305] = {row=2, col=3, maxRank=1, spells={900091}},
                    [2285] = {row=2, col=11, maxRank=1, spells={20135}},
                    [2276] = {row=2, col=12, maxRank=1, spells={900067}},
                    [2304] = {row=3, col=2, maxRank=1, spells={51886}},
                    [2306] = {row=3, col=3, maxRank=1, spells={900093}},
                    [2287] = {row=3, col=11, maxRank=1, spells={47296}},
                    [2279] = {row=3, col=12, maxRank=1, spells={900066}},
                    [2301] = {row=4, col=2, maxRank=1, spells={57994}},
                    [2307] = {row=4, col=3, maxRank=1, spells={900095}},
                    [2288] = {row=4, col=11, maxRank=1, spells={58874}},
                    [2278] = {row=4, col=12, maxRank=1, spells={900065}},
                    [2302] = {row=5, col=2, maxRank=1, spells={66842}},
                    [2277] = {row=5, col=12, maxRank=1, spells={900064}},
                    [2299] = {row=6, col=12, maxRank=1, spells={900055}},
                    [2296] = {row=7, col=12, maxRank=1, spells={900051}},
                    [2297] = {row=8, col=12, maxRank=1, spells={900052}},
                    [2298] = {row=9, col=12, maxRank=1, spells={900053}},
                    [2274] = {row=10, col=12, maxRank=1, spells={900054}},
                    [2272] = {row=11, col=4, maxRank=1, spells={900045}, mastery=true},
                },  -- talents
            },  -- Primal Conduit
        },  -- tabs
    },  -- SHAMAN

    -- ══ MAGE (classId=8) ══
    [8] = {
        className = "MAGE",
        tabs = {
            [1] = {
                name = "Fire",
                tabId = 41,
                masteryTalentId = 23,
                talents = {
                    [2223] = {row=1, col=2, maxRank=1, spells={66}},
                    [23] = {row=1, col=4, maxRank=1, spells={12848}, mastery=true},
                    [1850] = {row=1, col=5, maxRank=3, spells={44445, 44446, 44448}},
                    [2235] = {row=1, col=7, maxRank=3, spells={44449, 44470, 44472}},
                    [2236] = {row=1, col=9, maxRank=2, spells={11367, 11368}},
                    [2230] = {row=1, col=12, maxRank=1, spells={11129}},
                    [2245] = {row=2, col=1, maxRank=1, spells={12503}},
                    [2224] = {row=2, col=2, maxRank=1, spells={55342}},
                    [2241] = {row=2, col=3, maxRank=1, spells={12577}},
                    [2232] = {row=2, col=12, maxRank=1, spells={42873}},
                    [2244] = {row=3, col=1, maxRank=1, spells={64357}},
                    [2225] = {row=3, col=2, maxRank=1, spells={1953}},
                    [2242] = {row=3, col=3, maxRank=1, spells={31572}},
                    [2239] = {row=3, col=11, maxRank=1, spells={900044}},
                    [2233] = {row=3, col=12, maxRank=1, spells={42926}},
                    [2243] = {row=4, col=1, maxRank=1, spells={31583}},
                    [2228] = {row=4, col=2, maxRank=1, spells={30449}},
                    [2237] = {row=4, col=3, maxRank=1, spells={29076}},
                    [2234] = {row=4, col=12, maxRank=1, spells={55360}},
                    [2231] = {row=5, col=12, maxRank=1, spells={42891}},
                },  -- talents
            },  -- Fire
            [2] = {
                name = "Arcane",
                tabId = 61,
                masteryTalentId = 37,
                talents = {
                    [2223] = {row=1, col=2, maxRank=1, spells={66}},
                    [38] = {row=1, col=4, maxRank=3, spells={11071, 12496, 12497}},
                    [61] = {row=1, col=5, maxRank=3, spells={11151, 12952, 12953}},
                    [65] = {row=1, col=6, maxRank=3, spells={11175, 12569, 12571}},
                    [73] = {row=1, col=7, maxRank=3, spells={11207, 12672, 15047}},
                    [741] = {row=1, col=8, maxRank=2, spells={16757, 16758}},
                    [1736] = {row=1, col=9, maxRank=3, spells={31667, 31668, 31669}},
                    [1737] = {row=1, col=10, maxRank=2, spells={55091, 55092}, prereqs={{id=72, rank=0}}},
                    [2245] = {row=2, col=1, maxRank=1, spells={12503}},
                    [2224] = {row=2, col=2, maxRank=1, spells={55342}},
                    [2241] = {row=2, col=3, maxRank=1, spells={12577}},
                    [1854] = {row=2, col=4, maxRank=3, spells={44546, 44548, 44549}},
                    [2214] = {row=2, col=5, maxRank=2, spells={44745, 54787}, prereqs={{id=71, rank=0}}},
                    [37] = {row=2, col=6, maxRank=5, spells={11070, 12473, 16763, 16765, 16766}, mastery=true},
                    [66] = {row=2, col=7, maxRank=3, spells={11160, 12518, 12519}},
                    [69] = {row=2, col=8, maxRank=1, spells={12472}, flags=1},
                    [70] = {row=2, col=9, maxRank=2, spells={11189, 28332}},
                    [71] = {row=2, col=10, maxRank=1, spells={11426}, prereqs={{id=72, rank=0}}, flags=1},
                    [2244] = {row=3, col=1, maxRank=1, spells={64357}},
                    [2225] = {row=3, col=2, maxRank=1, spells={1953}},
                    [2242] = {row=3, col=3, maxRank=1, spells={31572}},
                    [72] = {row=3, col=4, maxRank=1, spells={11958}, flags=1},
                    [1740] = {row=3, col=5, maxRank=2, spells={31682, 31683}},
                    [1741] = {row=3, col=6, maxRank=1, spells={31687}, flags=1},
                    [1856] = {row=3, col=7, maxRank=5, spells={44566, 44567, 44568, 44570, 44571}},
                    [1857] = {row=3, col=8, maxRank=1, spells={44572}, flags=1},
                    [62] = {row=3, col=9, maxRank=3, spells={31670, 31672, 55094}},
                    [63] = {row=3, col=10, maxRank=3, spells={11185, 12487, 12488}},
                    [2243] = {row=4, col=1, maxRank=1, spells={31583}},
                    [2228] = {row=4, col=2, maxRank=1, spells={30449}},
                    [2237] = {row=4, col=3, maxRank=1, spells={29076}},
                    [64] = {row=4, col=4, maxRank=3, spells={11190, 12489, 12490}},
                    [67] = {row=4, col=5, maxRank=3, spells={11170, 12982, 12983}},
                    [68] = {row=4, col=6, maxRank=3, spells={11180, 28592, 28593}},
                    [1649] = {row=4, col=7, maxRank=3, spells={29438, 29439, 29440}},
                    [1738] = {row=4, col=8, maxRank=5, spells={31674, 31675, 31676, 31677, 31678}},
                    [1853] = {row=4, col=9, maxRank=2, spells={44543, 44545}},
                    [1855] = {row=4, col=10, maxRank=3, spells={44557, 44560, 44561}, prereqs={{id=1741, rank=0}}},
                },  -- talents
            },  -- Arcane
            [3] = {
                name = "Frost",
                tabId = 81,
                masteryTalentId = 74,
                talents = {
                    [2223] = {row=1, col=2, maxRank=1, spells={66}},
                    [74] = {row=1, col=4, maxRank=2, spells={11210, 12592}, mastery=true},
                    [77] = {row=1, col=5, maxRank=5, spells={11232, 12500, 12501, 12502, 12503}},
                    [82] = {row=1, col=6, maxRank=2, spells={11247, 12606}},
                    [83] = {row=1, col=7, maxRank=2, spells={11252, 12605}},
                    [85] = {row=1, col=8, maxRank=3, spells={28574, 54658, 54659}},
                    [1724] = {row=1, col=9, maxRank=2, spells={31569, 31570}},
                    [1726] = {row=1, col=10, maxRank=3, spells={31574, 31575, 54354}},
                    [2245] = {row=2, col=1, maxRank=1, spells={12503}},
                    [2224] = {row=2, col=2, maxRank=1, spells={55342}},
                    [2241] = {row=2, col=3, maxRank=1, spells={12577}},
                    [1727] = {row=2, col=4, maxRank=3, spells={31579, 31582, 31583}},
                    [2211] = {row=2, col=5, maxRank=1, spells={54646}, flags=1},
                    [2222] = {row=2, col=6, maxRank=3, spells={29447, 55339, 55340}},
                    [76] = {row=2, col=7, maxRank=3, spells={11222, 12839, 12840}},
                    [81] = {row=2, col=8, maxRank=3, spells={11242, 12467, 12469}},
                    [86] = {row=2, col=9, maxRank=1, spells={12043}, flags=1},
                    [87] = {row=2, col=10, maxRank=1, spells={12042}, prereqs={{id=421, rank=2}}, flags=1},
                    [2244] = {row=3, col=1, maxRank=1, spells={64357}},
                    [2225] = {row=3, col=2, maxRank=1, spells={1953}},
                    [2242] = {row=3, col=3, maxRank=1, spells={31572}},
                    [88] = {row=3, col=4, maxRank=2, spells={11255, 12598}},
                    [421] = {row=3, col=5, maxRank=3, spells={15058, 15059, 15060}, prereqs={{id=86, rank=0}}},
                    [1650] = {row=3, col=6, maxRank=2, spells={29441, 29444}},
                    [1729] = {row=3, col=7, maxRank=1, spells={31589}, flags=1},
                    [1843] = {row=3, col=8, maxRank=2, spells={44378, 44379}, prereqs={{id=87, rank=0}}},
                    [1846] = {row=3, col=9, maxRank=3, spells={44400, 44402, 44403}},
                    [1847] = {row=3, col=10, maxRank=1, spells={44425}, flags=1},
                    [2243] = {row=4, col=1, maxRank=1, spells={31583}},
                    [2228] = {row=4, col=2, maxRank=1, spells={30449}},
                    [2237] = {row=4, col=3, maxRank=1, spells={29076}},
                    [75] = {row=4, col=4, maxRank=5, spells={11213, 12574, 12575, 12576, 12577}},
                    [80] = {row=4, col=5, maxRank=5, spells={11237, 12463, 12464, 16769, 16770}},
                    [1142] = {row=4, col=6, maxRank=3, spells={18462, 18463, 18464}},
                    [1725] = {row=4, col=7, maxRank=2, spells={31571, 31572}, prereqs={{id=86, rank=0}}},
                    [1728] = {row=4, col=8, maxRank=5, spells={31584, 31585, 31586, 31587, 31588}},
                    [1826] = {row=4, col=9, maxRank=2, spells={35578, 35581}},
                    [1844] = {row=4, col=10, maxRank=3, spells={44394, 44395, 44396}},
                    [1845] = {row=5, col=4, maxRank=3, spells={44397, 44398, 44399}},
                    [2209] = {row=5, col=5, maxRank=5, spells={44404, 54486, 54488, 54489, 54490}},
                },  -- talents
            },  -- Frost
        },  -- tabs
    },  -- MAGE

    -- ══ WARLOCK (classId=9) ══
    [9] = {
        className = "WARLOCK",
        tabs = {
            [1] = {
                name = "Vengance",
                tabId = 301,
                masteryTalentId = 2263,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                },  -- talents
            },  -- Vengance
            [2] = {
                name = "Affliction",
                tabId = 302,
                masteryTalentId = 2263,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                },  -- talents
            },  -- Affliction
            [3] = {
                name = "Demonology",
                tabId = 303,
                masteryTalentId = 2273,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                    [1001] = {row=1, col=12, maxRank=1, spells={47241}},
                    [2266] = {row=2, col=11, maxRank=1, spells={18768}},
                    [2264] = {row=2, col=12, maxRank=1, spells={603}},
                    [2283] = {row=2, col=13, maxRank=1, spells={17803}},
                    [2265] = {row=3, col=11, maxRank=1, spells={47231}},
                    [2280] = {row=3, col=13, maxRank=1, spells={47247}},
                    [2273] = {row=4, col=6, maxRank=1, spells={47240}, mastery=true},
                    [2267] = {row=4, col=11, maxRank=1, spells={18693}},
                    [2262] = {row=4, col=12, maxRank=1, spells={6353}},
                    [2282] = {row=4, col=13, maxRank=1, spells={59741}},
                    [2272] = {row=5, col=12, maxRank=1, spells={47193}},
                },  -- talents
            },  -- Demonology
            [4] = {
                name = "Destruction",
                tabId = 10094,
                masteryTalentId = 2263,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                },  -- talents
            },  -- Destruction
            [5] = {
                name = "Havoc",
                tabId = 10095,
                masteryTalentId = 2263,
                talents = {
                    [2263] = {row=1, col=2, maxRank=1, spells={172}},
                },  -- talents
            },  -- Havoc
        },  -- tabs
    },  -- WARLOCK

    -- ══ DRUID (classId=11) ══
    [11] = {
        className = "DRUID",
        tabs = {
            [1] = {
                name = "Balance",
                tabId = 281,
                masteryTalentId = 794,
                talents = {
                    [2270] = {row=1, col=2, maxRank=1, spells={768}},
                    [797] = {row=1, col=4, maxRank=2, spells={16940, 16941}},
                    [799] = {row=1, col=5, maxRank=3, spells={16947, 16948, 16949}},
                    [802] = {row=1, col=6, maxRank=2, spells={16966, 16968}},
                    [807] = {row=1, col=7, maxRank=2, spells={17002, 24866}},
                    [1792] = {row=1, col=8, maxRank=2, spells={33872, 33873}},
                    [1793] = {row=1, col=9, maxRank=3, spells={33851, 33852, 33957}},
                    [1914] = {row=1, col=10, maxRank=2, spells={48409, 48410}, prereqs={{id=798, rank=2}}},
                    [2281] = {row=1, col=12, maxRank=1, spells={48505}},
                    [2269] = {row=2, col=1, maxRank=1, spells={24858}},
                    [2268] = {row=2, col=2, maxRank=1, spells={9634}},
                    [2271] = {row=2, col=3, maxRank=1, spells={33891}},
                    [1919] = {row=2, col=4, maxRank=3, spells={48483, 48484, 48485}},
                    [1921] = {row=2, col=5, maxRank=3, spells={48492, 48494, 48495}},
                    [2241] = {row=2, col=6, maxRank=3, spells={57873, 57876, 57877}, prereqs={{id=809, rank=0}}},
                    [2242] = {row=2, col=7, maxRank=3, spells={57878, 57880, 57881}},
                    [796] = {row=2, col=8, maxRank=5, spells={16934, 16935, 16936, 16937, 16938}},
                    [803] = {row=2, col=9, maxRank=3, spells={16972, 16974, 16975}},
                    [805] = {row=2, col=10, maxRank=2, spells={16998, 16999}},
                    [2282] = {row=2, col=11, maxRank=1, spells={2912}},
                    [2279] = {row=2, col=12, maxRank=1, spells={8921}},
                    [2280] = {row=2, col=13, maxRank=1, spells={5570}},
                    [2273] = {row=3, col=1, maxRank=1, spells={48396}},
                    [2274] = {row=3, col=2, maxRank=1, spells={48412}},
                    [2272] = {row=3, col=3, maxRank=1, spells={48537}},
                    [808] = {row=3, col=4, maxRank=5, spells={17003, 17004, 17005, 17006, 24894}, prereqs={{id=803, rank=2}}},
                    [809] = {row=3, col=5, maxRank=1, spells={17007}, flags=1},
                    [1162] = {row=3, col=6, maxRank=1, spells={61336}, flags=1},
                    [1796] = {row=3, col=7, maxRank=1, spells={33917}, prereqs={{id=809, rank=0}}},
                    [1918] = {row=3, col=8, maxRank=5, spells={48432, 48433, 48434, 51268, 51269}},
                    [1927] = {row=3, col=9, maxRank=1, spells={50334}, flags=1},
                    [794] = {row=3, col=10, maxRank=1, spells={33607}, mastery=true},
                    [2286] = {row=3, col=11, maxRank=1, spells={16924}},
                    [2289] = {row=3, col=12, maxRank=1, spells={48511}},
                    [2283] = {row=3, col=13, maxRank=1, spells={57851}},
                    [2276] = {row=4, col=1, maxRank=1, spells={16913}},
                    [2277] = {row=4, col=2, maxRank=1, spells={51269}},
                    [2278] = {row=4, col=3, maxRank=1, spells={51183}},
                    [795] = {row=4, col=4, maxRank=5, spells={16858, 16859, 16860, 16861, 16862}},
                    [798] = {row=4, col=5, maxRank=3, spells={16942, 16943, 16944}},
                    [801] = {row=4, col=6, maxRank=2, spells={37116, 37117}, prereqs={{id=798, rank=2}}},
                    [804] = {row=4, col=7, maxRank=1, spells={49377}},
                    [1794] = {row=4, col=8, maxRank=3, spells={33853, 33855, 33856}},
                    [1795] = {row=4, col=9, maxRank=3, spells={33859, 33866, 33867}},
                    [1798] = {row=4, col=10, maxRank=2, spells={34297, 34300}, prereqs={{id=809, rank=0}}},
                    [2288] = {row=4, col=11, maxRank=1, spells={33956}},
                    [2284] = {row=4, col=12, maxRank=1, spells={61346}},
                    [2287] = {row=4, col=13, maxRank=1, spells={16818}},
                    [2275] = {row=5, col=2, maxRank=1, spells={40120}},
                    [1920] = {row=5, col=4, maxRank=3, spells={48532, 48489, 48491}, prereqs={{id=1796, rank=0}}},
                    [2266] = {row=5, col=5, maxRank=1, spells={63503}, prereqs={{id=1918, rank=4}}},
                    [2285] = {row=5, col=12, maxRank=1, spells={33831}},
                },  -- talents
            },  -- Balance
            [2] = {
                name = "Feral",
                tabId = 282,
                masteryTalentId = 821,
                talents = {
                    [2270] = {row=1, col=2, maxRank=1, spells={768}},
                    [821] = {row=1, col=4, maxRank=2, spells={17050, 17051}, mastery=true},
                    [824] = {row=1, col=5, maxRank=5, spells={17069, 17070, 17071, 17072, 17073}},
                    [829] = {row=1, col=6, maxRank=3, spells={17106, 17107, 17108}},
                    [831] = {row=1, col=7, maxRank=1, spells={17116}, prereqs={{id=829, rank=2}}, flags=1},
                    [842] = {row=1, col=8, maxRank=2, spells={17123, 17124}},
                    [1788] = {row=1, col=9, maxRank=2, spells={33879, 33880}},
                    [1797] = {row=1, col=10, maxRank=3, spells={34151, 34152, 34153}},
                    [2269] = {row=2, col=1, maxRank=1, spells={24858}},
                    [2268] = {row=2, col=2, maxRank=1, spells={9634}},
                    [2271] = {row=2, col=3, maxRank=1, spells={33891}},
                    [1929] = {row=2, col=4, maxRank=3, spells={48539, 48544, 48545}},
                    [2264] = {row=2, col=5, maxRank=2, spells={63410, 63411}},
                    [823] = {row=2, col=6, maxRank=3, spells={17063, 17065, 17066}},
                    [827] = {row=2, col=7, maxRank=1, spells={16864}},
                    [828] = {row=2, col=8, maxRank=5, spells={17104, 24943, 24944, 24945, 24946}},
                    [841] = {row=2, col=9, maxRank=3, spells={17118, 17119, 17120}},
                    [843] = {row=2, col=10, maxRank=5, spells={24968, 24969, 24970, 24971, 24972}},
                    [2273] = {row=3, col=1, maxRank=1, spells={48396}},
                    [2274] = {row=3, col=2, maxRank=1, spells={48412}},
                    [2272] = {row=3, col=3, maxRank=1, spells={48537}},
                    [844] = {row=3, col=4, maxRank=1, spells={18562}, prereqs={{id=828, rank=4}}, flags=1},
                    [1789] = {row=3, col=5, maxRank=5, spells={33886, 33887, 33888, 33889, 33890}},
                    [1791] = {row=3, col=6, maxRank=1, spells={65139}, prereqs={{id=1789, rank=4}}, flags=1},
                    [1917] = {row=3, col=7, maxRank=1, spells={48438}, prereqs={{id=1791, rank=0}}, flags=1},
                    [822] = {row=3, col=8, maxRank=5, spells={17056, 17058, 17059, 17060, 17061}},
                    [825] = {row=3, col=9, maxRank=5, spells={17074, 17075, 17076, 17077, 17078}, prereqs={{id=830, rank=2}}},
                    [826] = {row=3, col=10, maxRank=3, spells={16833, 16834, 16835}},
                    [2276] = {row=4, col=1, maxRank=1, spells={16913}},
                    [2277] = {row=4, col=2, maxRank=1, spells={51269}},
                    [2278] = {row=4, col=3, maxRank=1, spells={51183}},
                    [830] = {row=4, col=4, maxRank=3, spells={17111, 17112, 17113}},
                    [1790] = {row=4, col=5, maxRank=3, spells={33881, 33882, 33883}},
                    [1915] = {row=4, col=6, maxRank=2, spells={48411, 48412}, prereqs={{id=826, rank=2}}},
                    [1916] = {row=4, col=7, maxRank=5, spells={51179, 51180, 51181, 51182, 51183}},
                    [1922] = {row=4, col=8, maxRank=3, spells={48496, 48499, 48500}},
                    [1930] = {row=4, col=9, maxRank=3, spells={48535, 48536, 48537}, prereqs={{id=1791, rank=0}}},
                    [2275] = {row=5, col=2, maxRank=1, spells={40120}},
                },  -- talents
            },  -- Feral
            [3] = {
                name = "Restoration",
                tabId = 283,
                masteryTalentId = 762,
                talents = {
                    [2270] = {row=1, col=2, maxRank=1, spells={768}},
                    [763] = {row=1, col=4, maxRank=2, spells={16821, 16822}},
                    [764] = {row=1, col=5, maxRank=2, spells={16819, 16820}},
                    [782] = {row=1, col=6, maxRank=3, spells={16836, 16839, 16840}},
                    [783] = {row=1, col=7, maxRank=3, spells={16845, 16846, 16847}},
                    [1782] = {row=1, col=8, maxRank=3, spells={33589, 33590, 33591}},
                    [1784] = {row=1, col=9, maxRank=3, spells={33597, 33599, 33956}},
                    [1785] = {row=1, col=10, maxRank=3, spells={33600, 33601, 33602}},
                    [2269] = {row=2, col=1, maxRank=1, spells={24858}},
                    [2268] = {row=2, col=2, maxRank=1, spells={9634}},
                    [2271] = {row=2, col=3, maxRank=1, spells={33891}},
                    [1913] = {row=2, col=4, maxRank=3, spells={48389, 48392, 48393}, prereqs={{id=793, rank=0}}},
                    [1924] = {row=2, col=5, maxRank=3, spells={48516, 48521, 48525}},
                    [1925] = {row=2, col=6, maxRank=2, spells={48488, 48514}},
                    [762] = {row=2, col=7, maxRank=5, spells={16814, 16815, 16816, 16817, 16818}, mastery=true},
                    [788] = {row=2, col=8, maxRank=1, spells={5570}, flags=1},
                    [789] = {row=2, col=9, maxRank=3, spells={16880, 61345, 61346}, prereqs={{id=1822, rank=1}}},
                    [790] = {row=2, col=10, maxRank=3, spells={16896, 16897, 16899}},
                    [2273] = {row=3, col=1, maxRank=1, spells={48396}},
                    [2274] = {row=3, col=2, maxRank=1, spells={48412}},
                    [2272] = {row=3, col=3, maxRank=1, spells={48537}},
                    [792] = {row=3, col=4, maxRank=5, spells={16909, 16910, 16911, 16912, 16913}},
                    [793] = {row=3, col=5, maxRank=1, spells={24858}, flags=1},
                    [1822] = {row=3, col=6, maxRank=2, spells={35363, 35364}},
                    [1923] = {row=3, col=7, maxRank=1, spells={50516}, prereqs={{id=793, rank=0}}, flags=1},
                    [1926] = {row=3, col=8, maxRank=1, spells={48505}, flags=1},
                    [1928] = {row=3, col=9, maxRank=3, spells={48506, 48510, 48511}},
                    [784] = {row=3, col=10, maxRank=3, spells={16850, 16923, 16924}},
                    [2276] = {row=4, col=1, maxRank=1, spells={16913}},
                    [2277] = {row=4, col=2, maxRank=1, spells={51269}},
                    [2278] = {row=4, col=3, maxRank=1, spells={51183}},
                    [1783] = {row=4, col=4, maxRank=2, spells={33592, 33596}},
                    [1786] = {row=4, col=5, maxRank=5, spells={33603, 33604, 33605, 33606, 33607}},
                    [1787] = {row=4, col=6, maxRank=1, spells={33831}, flags=1},
                    [1912] = {row=4, col=7, maxRank=3, spells={48384, 48395, 48396}, prereqs={{id=793, rank=0}}},
                    [2238] = {row=4, col=8, maxRank=5, spells={57810, 57811, 57812, 57813, 57814}},
                    [2239] = {row=4, col=9, maxRank=3, spells={57849, 57850, 57851}, prereqs={{id=788, rank=0}}},
                    [2240] = {row=4, col=10, maxRank=1, spells={57865}, prereqs={{id=1822, rank=1}}},
                    [2275] = {row=5, col=2, maxRank=1, spells={40120}},
                },  -- talents
            },  -- Restoration
            [4] = {
                name = "Guardian",
                tabId = 10114,
                masteryTalentId = 2268,
                talents = {
                    [2270] = {row=1, col=2, maxRank=1, spells={768}},
                    [2269] = {row=2, col=1, maxRank=1, spells={24858}},
                    [2268] = {row=2, col=2, maxRank=1, spells={9634}},
                    [2271] = {row=2, col=3, maxRank=1, spells={33891}},
                    [2273] = {row=3, col=1, maxRank=1, spells={48396}},
                    [2274] = {row=3, col=2, maxRank=1, spells={48412}},
                    [2272] = {row=3, col=3, maxRank=1, spells={48537}},
                    [2276] = {row=4, col=1, maxRank=1, spells={16913}},
                    [2277] = {row=4, col=2, maxRank=1, spells={51269}},
                    [2278] = {row=4, col=3, maxRank=1, spells={51183}},
                    [2275] = {row=5, col=2, maxRank=1, spells={40120}},
                },  -- talents
            },  -- Guardian
        },  -- tabs
    },  -- DRUID

}  -- SURREAL_TALENT_TREES
